const transactions = [
  {
    id: 1,
    name: "Amazon",
    type: "Shopping",
    amount: -150.32,
    date: "2 Oct 2025, 14:32",
    status: "completed",
    icon: "fa-shopping-cart",
    color: "bg-orange-100 text-orange-600",
  },
  {
    id: 2,
    name: "Salary Deposit",
    type: "Income",
    amount: 2500.0,
    date: "1 Oct 2025, 09:00",
    status: "completed",
    icon: "fa-dollar-sign",
    color: "bg-green-100 text-green-600",
  },
  {
    id: 3,
    name: "Netflix",
    type: "Subscription",
    amount: -15.99,
    date: "1 Oct 2025, 08:15",
    status: "completed",
    icon: "fa-tv",
    color: "bg-red-100 text-red-600",
  },
  {
    id: 4,
    name: "Payment",
    type: "Transfer",
    amount: -89.0,
    date: "30 Sep 2025, 18:45",
    status: "pending",
    icon: "fa-exchange-alt",
    color: "bg-yellow-100 text-yellow-600",
  },
  {
    id: 5,
    name: "Uber",
    type: "Transport",
    amount: -12.5,
    date: "30 Sep 2025, 12:20",
    status: "completed",
    icon: "fa-car",
    color: "bg-gray-100 text-gray-600",
  },
  {
    id: 6,
    name: "Starbucks",
    type: "Food & Drink",
    amount: -7.85,
    date: "29 Sep 2025, 08:30",
    status: "completed",
    icon: "fa-coffee",
    color: "bg-green-100 text-green-700",
  },
  {
    id: 7,
    name: "Refund",
    type: "Refund",
    amount: 45.0,
    date: "28 Sep 2025, 16:00",
    status: "completed",
    icon: "fa-undo",
    color: "bg-blue-100 text-blue-600",
  },
];
export default transactions;
